//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class ActividadMantenimientoPredictivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActividadMantenimientoPredictivo()
        {
            this.MantenimientoPredictivoMaterial = new HashSet<MantenimientoPredictivoMaterial>();
            this.MantenimientoPredictivoPuesto = new HashSet<MantenimientoPredictivoPuesto>();
            this.MantenimientoPredictivoRefaccion = new HashSet<MantenimientoPredictivoRefaccion>();
        }
    
        public int IdActividadMantenimientoPredictivo { get; set; }
        public int IdDetalleMantenimientoPredictivo { get; set; }
        public int IdSistema { get; set; }
        public int IdElemento { get; set; }
        public string Descripcion { get; set; }
        public double Tiempo { get; set; }
        public Nullable<bool> Ejecutada { get; set; }
    
        public virtual DetalleMantenimientoPredictivo DetalleMantenimientoPredictivo { get; set; }
        public virtual Elemento Elemento { get; set; }
        public virtual Sistema Sistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoMaterial> MantenimientoPredictivoMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoPuesto> MantenimientoPredictivoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoRefaccion> MantenimientoPredictivoRefaccion { get; set; }
    }
}
