//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class AlertaNivelUsuario
    {
        public int IdAlertaNivelUsuario { get; set; }
        public int IdAlertaMensaje { get; set; }
        public int IdNivelUsuario { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual AlertaMensaje AlertaMensaje { get; set; }
        public virtual NivelUsuario NivelUsuario { get; set; }
    }
}
