//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class AlertaMensaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertaMensaje()
        {
            this.AlertaNivelUsuario = new HashSet<AlertaNivelUsuario>();
        }
    
        public int IdAlertaMensaje { get; set; }
        public int IdAlerta { get; set; }
        public int IdMensaje { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual Alerta Alerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertaNivelUsuario> AlertaNivelUsuario { get; set; }
    }
}
