//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class BackLogMaterial
    {
        public int IdBackLogMaterial { get; set; }
        public int IdBackLog { get; set; }
        public string IdMaterial { get; set; }
        public double Cantidad { get; set; }
    
        public virtual BackLog BackLog { get; set; }
        public virtual Material Material { get; set; }
    }
}
