//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class BackLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BackLog()
        {
            this.BackLogMaterial = new HashSet<BackLogMaterial>();
            this.BackLogPuesto = new HashSet<BackLogPuesto>();
            this.BackLogRefaccion = new HashSet<BackLogRefaccion>();
            this.DetalleOrdenTrabajo = new HashSet<DetalleOrdenTrabajo>();
        }
    
        public int IdBackLog { get; set; }
        public int IdUnidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdSistema { get; set; }
        public int IdElemento { get; set; }
        public string Actividad { get; set; }
        public double Tiempo { get; set; }
        public Nullable<bool> Ejecutada { get; set; }
    
        public virtual Elemento Elemento { get; set; }
        public virtual Sistema Sistema { get; set; }
        public virtual Unidad Unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackLogMaterial> BackLogMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackLogPuesto> BackLogPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackLogRefaccion> BackLogRefaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenTrabajo> DetalleOrdenTrabajo { get; set; }
    }
}
