//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class CaracteristicasUnidad
    {
        public int IdCaracteristica { get; set; }
        public int IdUnidad { get; set; }
        public Nullable<int> CapacidadCombustible { get; set; }
        public Nullable<int> CapacidadAceite_Motor { get; set; }
        public Nullable<int> CapacidadTransmision { get; set; }
        public Nullable<int> CapacidadMandos { get; set; }
        public Nullable<int> CapacidadEnfriamiento { get; set; }
        public string TipoMotor { get; set; }
        public Nullable<int> NumeroCilindros { get; set; }
        public int CapacidadCarga { get; set; }
        public string Potencia { get; set; }
        public string Torque { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual Unidad Unidad { get; set; }
    }
}
