//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class CatalogoEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogoEvento()
        {
            this.EventosGuiaInspeccion = new HashSet<EventosGuiaInspeccion>();
        }
    
        public int IdCatalogoEvento { get; set; }
        public int IdArea { get; set; }
        public int IdTipoEvento { get; set; }
        public int CodigoEvento { get; set; }
        public string DescripcionEvento { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventosGuiaInspeccion> EventosGuiaInspeccion { get; set; }
    }
}
