//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int IdExperiencia { get; set; }
        public int IdTrabajador { get; set; }
        public string NombreCurso { get; set; }
        public int Horas { get; set; }
        public string Organizacion { get; set; }
        public System.DateTime FechaCurso { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    }
}
