//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleOrdenTrabajo()
        {
            this.PlanTrabajo = new HashSet<PlanTrabajo>();
        }
    
        public int IdDetalleOrdenTrabajo { get; set; }
        public int IdOrdenTrabajo { get; set; }
        public Nullable<int> IdGuiaServicio { get; set; }
        public Nullable<int> IdBackLog { get; set; }
        public Nullable<int> IdMantenimientoPredictivo { get; set; }
        public int IdTipoContrato { get; set; }
        public Nullable<int> IdContratoGarantia { get; set; }
        public string Factura { get; set; }
        public string TipoServicio { get; set; }
        public string Actividad { get; set; }
        public double Tiempo { get; set; }
        public int IdTipoActividad { get; set; }
        public string IdRefaccion { get; set; }
        public string IdMaterial { get; set; }
        public string IdPuesto { get; set; }
        public string Descripcion { get; set; }
        public double Costo { get; set; }
    
        public virtual BackLog BackLog { get; set; }
        public virtual ContratoGarantia ContratoGarantia { get; set; }
        public virtual GuiaServicio GuiaServicio { get; set; }
        public virtual MantenimientoPredictivo MantenimientoPredictivo { get; set; }
        public virtual Material Material { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual Refaccion Refaccion { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual TipoActividad TipoActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanTrabajo> PlanTrabajo { get; set; }
    }
}
