//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class DetalleGuiaServiciosRefaccion
    {
        public int IdDetalleGuiaServiciosRefaccion { get; set; }
        public int IdGuiaServicio { get; set; }
        public int IdDetalleGuiaServicio { get; set; }
        public string IdRefaccion { get; set; }
        public double Cantidad { get; set; }
    
        public virtual DetalleGuiaServicio DetalleGuiaServicio { get; set; }
        public virtual GuiaServicio GuiaServicio { get; set; }
        public virtual Refaccion Refaccion { get; set; }
    }
}
