//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class DetalleGuiaServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleGuiaServicio()
        {
            this.DetalleGuiaServiciosMaterial = new HashSet<DetalleGuiaServiciosMaterial>();
            this.DetalleGuiaServiciosPuesto = new HashSet<DetalleGuiaServiciosPuesto>();
            this.DetalleGuiaServiciosRefaccion = new HashSet<DetalleGuiaServiciosRefaccion>();
        }
    
        public int IdDetalleGuiaServicio { get; set; }
        public int IdGuiaServicio { get; set; }
        public int IdSistema { get; set; }
        public int IdElemento { get; set; }
        public string Actividad { get; set; }
        public double Tiempo { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosMaterial> DetalleGuiaServiciosMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosPuesto> DetalleGuiaServiciosPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosRefaccion> DetalleGuiaServiciosRefaccion { get; set; }
        public virtual Elemento Elemento { get; set; }
        public virtual GuiaServicio GuiaServicio { get; set; }
        public virtual Sistema Sistema { get; set; }
    }
}
