//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class DetalleMantenimientoPredictivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleMantenimientoPredictivo()
        {
            this.ActividadMantenimientoPredictivo = new HashSet<ActividadMantenimientoPredictivo>();
            this.MantenimientoPredictivoMaterial = new HashSet<MantenimientoPredictivoMaterial>();
            this.MantenimientoPredictivoPuesto = new HashSet<MantenimientoPredictivoPuesto>();
            this.MantenimientoPredictivoRefaccion = new HashSet<MantenimientoPredictivoRefaccion>();
            this.ResultadoMantenimientoPredictivo = new HashSet<ResultadoMantenimientoPredictivo>();
        }
    
        public int IdDetalleMantenimientoPredictivo { get; set; }
        public int IdMantenimientoPredictivo { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public double LimiteInf { get; set; }
        public double LimiteSup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadMantenimientoPredictivo> ActividadMantenimientoPredictivo { get; set; }
        public virtual MantenimientoPredictivo MantenimientoPredictivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoMaterial> MantenimientoPredictivoMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoPuesto> MantenimientoPredictivoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoRefaccion> MantenimientoPredictivoRefaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoMantenimientoPredictivo> ResultadoMantenimientoPredictivo { get; set; }
    }
}
