//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConnection : DbContext
    {
        public DBConnection()
            : base("name=DBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActividadMantenimientoPredictivo> ActividadMantenimientoPredictivo { get; set; }
        public virtual DbSet<Alerta> Alerta { get; set; }
        public virtual DbSet<AlertaMensaje> AlertaMensaje { get; set; }
        public virtual DbSet<AlertaNivelUsuario> AlertaNivelUsuario { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<BackLog> BackLog { get; set; }
        public virtual DbSet<BackLogMaterial> BackLogMaterial { get; set; }
        public virtual DbSet<BackLogPuesto> BackLogPuesto { get; set; }
        public virtual DbSet<BackLogRefaccion> BackLogRefaccion { get; set; }
        public virtual DbSet<CaracteristicasUnidad> CaracteristicasUnidad { get; set; }
        public virtual DbSet<CatalogoEvento> CatalogoEvento { get; set; }
        public virtual DbSet<CategoriaUnidad> CategoriaUnidad { get; set; }
        public virtual DbSet<ContratoGarantia> ContratoGarantia { get; set; }
        public virtual DbSet<DetalleGuiaServicio> DetalleGuiaServicio { get; set; }
        public virtual DbSet<DetalleGuiaServiciosMaterial> DetalleGuiaServiciosMaterial { get; set; }
        public virtual DbSet<DetalleGuiaServiciosPuesto> DetalleGuiaServiciosPuesto { get; set; }
        public virtual DbSet<DetalleGuiaServiciosRefaccion> DetalleGuiaServiciosRefaccion { get; set; }
        public virtual DbSet<DetalleMantenimientoPredictivo> DetalleMantenimientoPredictivo { get; set; }
        public virtual DbSet<DetalleOrdenTrabajo> DetalleOrdenTrabajo { get; set; }
        public virtual DbSet<DetallePlanTrabajoTrabajador> DetallePlanTrabajoTrabajador { get; set; }
        public virtual DbSet<Elemento> Elemento { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EstadoGuiaInspeccion> EstadoGuiaInspeccion { get; set; }
        public virtual DbSet<EstatusOrdenTrabajo> EstatusOrdenTrabajo { get; set; }
        public virtual DbSet<EventosGuiaInspeccion> EventosGuiaInspeccion { get; set; }
        public virtual DbSet<GuiaInspeccion> GuiaInspeccion { get; set; }
        public virtual DbSet<GuiaServicio> GuiaServicio { get; set; }
        public virtual DbSet<IndicadorGuiaInspeccion> IndicadorGuiaInspeccion { get; set; }
        public virtual DbSet<InsumosGuiaInspeccion> InsumosGuiaInspeccion { get; set; }
        public virtual DbSet<MantenimientoPredictivo> MantenimientoPredictivo { get; set; }
        public virtual DbSet<MantenimientoPredictivoMaterial> MantenimientoPredictivoMaterial { get; set; }
        public virtual DbSet<MantenimientoPredictivoPuesto> MantenimientoPredictivoPuesto { get; set; }
        public virtual DbSet<MantenimientoPredictivoRefaccion> MantenimientoPredictivoRefaccion { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<NivelUsuario> NivelUsuario { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<OperacioneNivelUsuario> OperacioneNivelUsuario { get; set; }
        public virtual DbSet<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual DbSet<PlanTrabajo> PlanTrabajo { get; set; }
        public virtual DbSet<Proceso> Proceso { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Refaccion> Refaccion { get; set; }
        public virtual DbSet<ResultadoMantenimientoPredictivo> ResultadoMantenimientoPredictivo { get; set; }
        public virtual DbSet<Sistema> Sistema { get; set; }
        public virtual DbSet<SistemaRefacciones> SistemaRefacciones { get; set; }
        public virtual DbSet<SubProceso> SubProceso { get; set; }
        public virtual DbSet<TipoActividad> TipoActividad { get; set; }
        public virtual DbSet<TipoContrato> TipoContrato { get; set; }
        public virtual DbSet<TipoEvento> TipoEvento { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<TrabajadorArea> TrabajadorArea { get; set; }
        public virtual DbSet<TrabajadorProceso> TrabajadorProceso { get; set; }
        public virtual DbSet<TrabajadorSubProceso> TrabajadorSubProceso { get; set; }
        public virtual DbSet<TrabajadorUbicacion> TrabajadorUbicacion { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Unidad> Unidad { get; set; }
        public virtual DbSet<UnidadArea> UnidadArea { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedida { get; set; }
        public virtual DbSet<UnidadProceso> UnidadProceso { get; set; }
        public virtual DbSet<UnidadSubProceso> UnidadSubProceso { get; set; }
        public virtual DbSet<UnidadUbicacion> UnidadUbicacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioArea> UsuarioArea { get; set; }
        public virtual DbSet<UsuarioProceso> UsuarioProceso { get; set; }
        public virtual DbSet<UsuarioSubProceso> UsuarioSubProceso { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CategoriaDocumentacion> CategoriaDocumentacion { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<DiaFestivo> DiaFestivo { get; set; }
        public virtual DbSet<DispositivosLicenciaUsuario> DispositivosLicenciaUsuario { get; set; }
        public virtual DbSet<Documentacion> Documentacion { get; set; }
        public virtual DbSet<DocumentacionUnidad> DocumentacionUnidad { get; set; }
        public virtual DbSet<LicenciaUsuario> LicenciaUsuario { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<TrabajadorLicencia> TrabajadorLicencia { get; set; }
    }
}
