//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class GuiaServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuiaServicio()
        {
            this.DetalleGuiaServicio = new HashSet<DetalleGuiaServicio>();
            this.DetalleGuiaServiciosMaterial = new HashSet<DetalleGuiaServiciosMaterial>();
            this.DetalleGuiaServiciosPuesto = new HashSet<DetalleGuiaServiciosPuesto>();
            this.DetalleGuiaServiciosRefaccion = new HashSet<DetalleGuiaServiciosRefaccion>();
            this.DetalleOrdenTrabajo = new HashSet<DetalleOrdenTrabajo>();
        }
    
        public int IdGuiaServicio { get; set; }
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
        public int IdArea { get; set; }
        public int Km_Hr { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServicio> DetalleGuiaServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosMaterial> DetalleGuiaServiciosMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosPuesto> DetalleGuiaServiciosPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosRefaccion> DetalleGuiaServiciosRefaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenTrabajo> DetalleOrdenTrabajo { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
