//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class IndicadorGuiaInspeccion
    {
        public int IdIndicadorGuiaInspeccion { get; set; }
        public int IdGuiaInspeccion { get; set; }
        public int IdEstadoGuiaInspeccion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual EstadoGuiaInspeccion EstadoGuiaInspeccion { get; set; }
        public virtual GuiaInspeccion GuiaInspeccion { get; set; }
    }
}
