//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class InsumosGuiaInspeccion
    {
        public int IdInsumosGuiaInspeccion { get; set; }
        public int IdGuiaInspeccion { get; set; }
        public string IdMaterial { get; set; }
        public int Cantidad { get; set; }
        public int KM_HR { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual GuiaInspeccion GuiaInspeccion { get; set; }
        public virtual Material Material { get; set; }
    }
}
