//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class LicenciaUsuario
    {
        public int IdLicenciaUsuario { get; set; }
        public int IdUsuario { get; set; }
        public int IdUbicacion { get; set; }
        public System.DateTime FechaInicioLicencia { get; set; }
        public System.DateTime FechaFinLicencia { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    }
}
