//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class OperacioneNivelUsuario
    {
        public int IdOperacionesNivelUsuario { get; set; }
        public int IdNivelUsuario { get; set; }
        public int IdOperacion { get; set; }
        public bool Permitido { get; set; }
        public bool Agregar { get; set; }
        public bool Editar { get; set; }
        public bool Consultar { get; set; }
        public bool Eliminar { get; set; }
    
        public virtual NivelUsuario NivelUsuario { get; set; }
        public virtual Operacion Operacion { get; set; }
    }
}
