//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenTrabajo()
        {
            this.DetalleOrdenTrabajo = new HashSet<DetalleOrdenTrabajo>();
            this.PlanTrabajo = new HashSet<PlanTrabajo>();
        }
    
        public int IdOrdenTrabajo { get; set; }
        public int IdUnidad { get; set; }
        public int IdArea { get; set; }
        public int IdEstatusOrdenTrabajo { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<bool> Planeada { get; set; }
        public Nullable<System.DateTime> FechaEjecuccion { get; set; }
        public Nullable<bool> Ejecutada { get; set; }
        public Nullable<System.DateTime> FechaEjecucion { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenTrabajo> DetalleOrdenTrabajo { get; set; }
        public virtual EstatusOrdenTrabajo EstatusOrdenTrabajo { get; set; }
        public virtual Unidad Unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanTrabajo> PlanTrabajo { get; set; }
    }
}
