//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class PlanTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanTrabajo()
        {
            this.DetallePlanTrabajoTrabajador = new HashSet<DetallePlanTrabajoTrabajador>();
        }
    
        public int IdPlanTrabajo { get; set; }
        public int IdOrdenTrabajo { get; set; }
        public int IdDetalleOrdenTrabajo { get; set; }
        public int IdArea { get; set; }
        public string TipoServicio { get; set; }
        public string Actividad { get; set; }
        public double Tiempo { get; set; }
        public System.DateTime FechaPlanInicio { get; set; }
        public System.DateTime FechaPlanFin { get; set; }
        public System.TimeSpan Comienza { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual DetalleOrdenTrabajo DetalleOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePlanTrabajoTrabajador> DetallePlanTrabajoTrabajador { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
