//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puesto()
        {
            this.BackLogPuesto = new HashSet<BackLogPuesto>();
            this.DetalleGuiaServiciosPuesto = new HashSet<DetalleGuiaServiciosPuesto>();
            this.DetalleOrdenTrabajo = new HashSet<DetalleOrdenTrabajo>();
            this.MantenimientoPredictivoPuesto = new HashSet<MantenimientoPredictivoPuesto>();
            this.Trabajador = new HashSet<Trabajador>();
        }
    
        public string IdPuesto { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public int IdArea { get; set; }
        public string NombrePuesto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> CostoHora { get; set; }
        public Nullable<double> Salario { get; set; }
        public Nullable<double> HorasMes { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackLogPuesto> BackLogPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosPuesto> DetalleGuiaServiciosPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenTrabajo> DetalleOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoPuesto> MantenimientoPredictivoPuesto { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajador> Trabajador { get; set; }
    }
}
