//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Refaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refaccion()
        {
            this.BackLogRefaccion = new HashSet<BackLogRefaccion>();
            this.DetalleGuiaServiciosRefaccion = new HashSet<DetalleGuiaServiciosRefaccion>();
            this.DetalleOrdenTrabajo = new HashSet<DetalleOrdenTrabajo>();
            this.MantenimientoPredictivoRefaccion = new HashSet<MantenimientoPredictivoRefaccion>();
        }
    
        public string IdRefaccion { get; set; }
        public int IdSistemaRefacciones { get; set; }
        public int IdUnidadMedida { get; set; }
        public Nullable<long> NumeroParteRefaccion { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Posicion { get; set; }
        public double CostoUnidad { get; set; }
        public int Cantidad { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackLogRefaccion> BackLogRefaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGuiaServiciosRefaccion> DetalleGuiaServiciosRefaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenTrabajo> DetalleOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPredictivoRefaccion> MantenimientoPredictivoRefaccion { get; set; }
        public virtual SistemaRefacciones SistemaRefacciones { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
