//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class ResultadoMantenimientoPredictivo
    {
        public int IdResultadoMantenimientoPredictivo { get; set; }
        public int IdDetalleMantenimientoPredictivo { get; set; }
        public string Resultado { get; set; }
    
        public virtual DetalleMantenimientoPredictivo DetalleMantenimientoPredictivo { get; set; }
    }
}
