//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class TrabajadorLicencia
    {
        public int IdLicencia { get; set; }
        public int IdTrabajador { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public string TipoLicencia { get; set; }
        public string GrupoSanguineo { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    }
}
