//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.DetallePlanTrabajoTrabajador = new HashSet<DetallePlanTrabajoTrabajador>();
            this.GuiaInspeccion = new HashSet<GuiaInspeccion>();
            this.TrabajadorUbicacion = new HashSet<TrabajadorUbicacion>();
            this.TrabajadorArea = new HashSet<TrabajadorArea>();
            this.TrabajadorProceso = new HashSet<TrabajadorProceso>();
            this.TrabajadorSubProceso = new HashSet<TrabajadorSubProceso>();
        }
    
        public int IdTrabajador { get; set; }
        public string IdPuesto { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Calle { get; set; }
        public string NroExterior { get; set; }
        public string NroInterior { get; set; }
        public string Colonia { get; set; }
        public int CodigoPostal { get; set; }
        public string Localidad { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public int NroSeguro { get; set; }
        public string RFC { get; set; }
        public string NombreContactoEmergencia { get; set; }
        public string TelefonoContactoEmergencia { get; set; }
        public Nullable<bool> Activo_Inactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePlanTrabajoTrabajador> DetallePlanTrabajoTrabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuiaInspeccion> GuiaInspeccion { get; set; }
        public virtual Puesto Puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorUbicacion> TrabajadorUbicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorArea> TrabajadorArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorProceso> TrabajadorProceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorSubProceso> TrabajadorSubProceso { get; set; }
    }
}
